### ISSUE TITLE
Corrections for SPadv v1.1 on Play Store

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadvR3#87]
1. The logo must be changed.  Please use this logo:
![SPadv icn](https://user-images.githubusercontent.com/98855936/172919476-00f785ce-0c0b-43a1-bcfa-d1bab22a37e2.png)
2. Let's write the app name with no space between StoryProducer, like this:  "StoryProducer Advanced"
3. Under the main app name, rather than displaying the developer's name (Teach Team Advantage), I think it would be more appropriate to display "Tyndale Bible Translators" as a copyright holder. (The developer's name is displayed under Developer contact)
4. Under About / What's new, please include the following: "Initial release on store. Update copyright info.  WordLinks feature for tracking, researching and documenting key words. Image swap feature.  Better readability for subtitles.
5. App info changes:

- Version 1.1.x
- Required OS  Android 7.0 and up
- Offered by   Tyndale Bible Translators
6.  Data collection - Do we need to say that SPadv collects Registration info when it is submitted by the user?  Is the software set up to collect video file names of videos produced by users when/if their phone is online? (SIL's version of SP was set up this way and was the primary data collection strategy to learn how much the app was being utilized.)

Question: Why is the size of the release APK 40 MB when normally APKs are more like 78 MBs?

**Comment by techteam25** [comment]
these have been fixed or moved to a new issue
